package io.rightpad.daxplorer;

import io.rightpad.daxplorer.visualization.ChartPanel;
import io.rightpad.daxplorer.visualization.PointF;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

public class TestWindow
{
    public JPanel mainPanel;
    private JTextField chartHeightField;
    public ChartPanel chartPanel;

    public TestWindow()
    {
        this.chartPanel.setChartWidth(20);

        this.chartHeightField.addActionListener(new AbstractAction()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                chartPanel.setChartHeight(Integer.parseInt(chartHeightField.getText()));
                chartPanel.setPosition(new PointF(chartPanel.getPosition().getX(), -chartPanel.getChartHeight() / 2f));
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.setMinimumSize(new Dimension(1, 1));
        mainPanel.setPreferredSize(new Dimension(1, 1));
        chartPanel = new ChartPanel();
        mainPanel.add(chartPanel, BorderLayout.CENTER);
        chartHeightField = new JTextField();
        mainPanel.add(chartHeightField, BorderLayout.SOUTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() { return mainPanel; }
}
